version: '2'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  interface:
    build:
      context: .
      dockerfile: ./compose/interface/Dockerfile
    command: /gunicorn.sh
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "5000:80"
